Repository codestates-seb/seb41_main_015, pull requests merged in 2023-01, with the labels that each got.

#39 Feat/be/req002 - 요청 수정 기능 구현
  server/src/docs/asciidoc/index.adoc
  server/src/main/java/com/book/village/server/domain/request/controller/RequestController.java
  server/src/main/java/com/book/village/server/domain/request/dto/RequestDto.java
  server/src/main/java/com/book/village/server/domain/request/mapper/RequestMapper.java
  server/src/main/java/com/book/village/server/domain/request/service/RequestService.java
  server/src/main/java/com/book/village/server/global/exception/ExceptionCode.java
  server/src/test/java/com/book/village/server/domain/request/RequestControllerRestDocsTest.java
Labels: [BE]박종혁

#61 fix/be/req002 - mapper 클래스 일부수정
  server/src/main/java/com/book/village/server/domain/request/mapper/RequestMapper.java
Labels: [BE]박종혁

#98 Feat/fe/reqList
  client/src/App.js
  client/src/components/BookList.js
  client/src/components/ListHigh.js
  client/src/data/reqListData.json
  client/src/page/ReqList.js
  client/src/page/ShareList.js
Labels: [FE]김혜민

#130 Feat/be/star001
  server/src/docs/asciidoc/index.adoc
  server/src/main/java/com/book/village/server/domain/book/controller/BookController.java
  server/src/main/java/com/book/village/server/domain/book/dto/BookDto.java
  server/src/main/java/com/book/village/server/domain/book/entity/Book.java
  server/src/main/java/com/book/village/server/domain/book/mapper/BookMapper.java
  server/src/main/java/com/book/village/server/domain/book/repository/BookRepository.java
  server/src/main/java/com/book/village/server/domain/book/service/BookService.java
  server/src/main/java/com/book/village/server/domain/rate/controller/RateController.java
  server/src/main/java/com/book/village/server/domain/rate/dto/RateDto.java
  server/src/main/java/com/book/village/server/domain/rate/entity/Rate.java
  server/src/main/java/com/book/village/server/domain/rate/mapper/RateMapper.java
  server/src/main/java/com/book/village/server/domain/rate/repository/RateRepository.java
  server/src/main/java/com/book/village/server/domain/rate/service/RateService.java
  server/src/main/java/com/book/village/server/global/exception/ExceptionCode.java
  server/src/main/resources/static/docs/index.html
  server/src/test/java/com/book/village/server/domain/book/BookRestDocsTest.java
  server/src/test/java/com/book/village/server/domain/community/CommunityControllerRestDocsTest.java
  server/src/test/java/com/book/village/server/domain/rate/RateControllerRestDocsTest.java
Labels: [BE]채승윤

#126 Feat/be/borrow/get
  server/src/docs/asciidoc/index.adoc
  server/src/main/java/com/book/village/server/domain/borrow/controller/BorrowController.java
  server/src/main/java/com/book/village/server/domain/borrow/dto/BorrowDto.java
  server/src/main/java/com/book/village/server/domain/borrow/entity/Borrow.java
  server/src/main/java/com/book/village/server/domain/borrow/mapper/BorrowMapper.java
  server/src/main/java/com/book/village/server/domain/borrow/repository/BorrowRepository.java
  server/src/main/java/com/book/village/server/domain/borrow/service/BorrowService.java
  server/src/main/java/com/book/village/server/domain/borrowcomment/controller/BorrowCommentController.java
  server/src/main/java/com/book/village/server/domain/borrowcomment/dto/BorrowCommentDto.java
  server/src/main/java/com/book/village/server/domain/borrowcomment/entity/BorrowComment.java
  server/src/main/java/com/book/village/server/domain/borrowcomment/mapper/BorrowCommentMapper.java
  server/src/main/java/com/book/village/server/domain/borrowcomment/repository/BorrowCommentRepository.java
  server/src/main/java/com/book/village/server/domain/borrowcomment/service/BorrowCommentService.java
  server/src/main/java/com/book/village/server/global/exception/ExceptionCode.java
  server/src/main/java/com/book/village/server/global/response/PageResponseDto.java
  server/src/main/resources/static/docs/index.html
  server/src/test/java/com/book/village/server/domain/borrow/BorrowControllerRestDocsTest.java
  server/src/test/java/com/book/village/server/domain/borrow/controller/BorrowControllerRestDocsTest.java
  server/src/test/java/com/book/village/server/domain/borrowcomment/controller/BorrowCommentControllerRestDocsTest.java
Labels: [BE]김성수

#132 hotfix/be/req - request commit
  server/src/main/java/com/book/village/server/domain/request/controller/RequestController.java
Labels: [BE]박종혁

#141 Feat/fe/hyemin
  client/src/App.js
  client/src/components/BookList.js
  client/src/components/DetailForm.js
  client/src/components/Header.js
  client/src/components/ListHigh.js
  client/src/components/Paging.js
  client/src/page/CommonList.js
  client/src/page/ShareDetail.js
Labels: [FE]김혜민

#163 Feat/be/img002
  server/build.gradle
  server/src/docs/asciidoc/index.adoc
  server/src/main/java/com/book/village/server/auth/handler/OAuth2MemberSuccessHandler.java
  server/src/main/java/com/book/village/server/config/AwsS3Config.java
  server/src/main/java/com/book/village/server/domain/book/entity/Book.java
  server/src/main/java/com/book/village/server/domain/borrow/entity/Borrow.java
  server/src/main/java/com/book/village/server/domain/member/dto/MemberDto.java
  server/src/main/java/com/book/village/server/domain/member/entity/Member.java
  server/src/main/java/com/book/village/server/domain/member/repository/MemberRepository.java
  server/src/main/java/com/book/village/server/domain/member/service/MemberService.java
  server/src/main/java/com/book/village/server/domain/request/entity/Request.java
  server/src/main/java/com/book/village/server/image/AwsS3Controller.java
  server/src/main/java/com/book/village/server/image/AwsS3Service.java
  server/src/main/resources/application-prod.yml
  server/src/main/resources/application.yml
  server/src/main/resources/testImage/logo.png
  server/src/test/java/com/book/village/server/domain/image/AwsS3ControllerRestDocsTest.java
Labels: [BE]채승윤

#181 Feat/be/displaydeltet
  server/src/docs/asciidoc/index.adoc
  server/src/main/java/com/book/village/server/auth/handler/OAuth2MemberSuccessHandler.java
  server/src/main/java/com/book/village/server/domain/borrow/controller/BorrowController.java
  server/src/main/java/com/book/village/server/domain/borrow/dto/BorrowDto.java
  server/src/main/java/com/book/village/server/domain/borrow/entity/Borrow.java
  server/src/main/java/com/book/village/server/domain/borrow/mapper/BorrowMapper.java
  server/src/main/java/com/book/village/server/domain/borrow/repository/BorrowRepository.java
  server/src/main/java/com/book/village/server/domain/borrow/service/BorrowService.java
  server/src/main/java/com/book/village/server/domain/borrowcomment/controller/BorrowCommentController.java
  server/src/main/java/com/book/village/server/domain/borrowcomment/dto/BorrowCommentDto.java
  server/src/main/java/com/book/village/server/domain/borrowcomment/entity/BorrowComment.java
  server/src/main/java/com/book/village/server/domain/request/entity/Request.java
  server/src/main/resources/application-local.yml
  server/src/test/java/com/book/village/server/domain/borrow/controller/BorrowControllerRestDocsTest.java
Labels: [BE]김성수

#172 feat: add view field and rest api docs for view in community
  server/src/docs/asciidoc/index.adoc
  server/src/main/java/com/book/village/server/domain/community/controller/CommunityController.java
  server/src/main/java/com/book/village/server/domain/community/dto/CommunityDto.java
  server/src/main/java/com/book/village/server/domain/community/entity/Community.java
  server/src/main/java/com/book/village/server/domain/community/mapper/CommunityMapper.java
  server/src/main/java/com/book/village/server/domain/community_comment/dto/CommunityCommentDto.java
  server/src/test/java/com/book/village/server/domain/community/CommunityControllerRestDocsTest.java
  server/src/test/java/com/book/village/server/statistics/communityView/communityViewRestDocsTest.java
Labels: [BE]채승윤

#184 Feat/fe/hyemin
  client/src/components/BookList.js
  client/src/components/DetailForm.js
  client/src/components/NicknameModal.js
  client/src/components/ShareStatus.js
  client/src/components/ToggleSwitch.js
  client/src/image/eye.svg
Labels: [FE]김혜민

#183 Refactor/be/views
  server/src/docs/asciidoc/index.adoc
  server/src/main/java/com/book/village/server/domain/request/controller/RequestController.java
  server/src/main/java/com/book/village/server/domain/request/dto/RequestDto.java
  server/src/main/java/com/book/village/server/domain/request/entity/Request.java
  server/src/main/java/com/book/village/server/domain/request/entity/RequestRank.java
  server/src/main/java/com/book/village/server/domain/request/mapper/RequestMapper.java
  server/src/main/java/com/book/village/server/domain/request/repository/RequestRepository.java
  server/src/main/java/com/book/village/server/domain/request/service/RequestService.java
  server/src/test/java/com/book/village/server/domain/request/RequestControllerRestDocsTest.java
  server/src/test/java/com/book/village/server/statistics/RequestRank/requestRankRestDocsTest.java
Labels: [BE]박종혁

#193 add rate ranking feature
  server/src/docs/asciidoc/index.adoc
  server/src/test/java/com/book/village/server/statistics/rating/ratingRestDocsTest.java
Labels: [BE]채승윤

#199 Feat/be/borrow rank
  server/src/docs/asciidoc/index.adoc
  server/src/main/java/com/book/village/server/domain/borrow/controller/BorrowController.java
  server/src/main/java/com/book/village/server/domain/borrow/dto/BorrowDto.java
  server/src/main/java/com/book/village/server/domain/borrow/entity/Borrow.java
  server/src/main/java/com/book/village/server/domain/borrow/entity/BorrowRank.java
  server/src/main/java/com/book/village/server/domain/borrow/mapper/BorrowMapper.java
  server/src/main/java/com/book/village/server/domain/borrow/repository/BorrowRepository.java
  server/src/main/java/com/book/village/server/domain/borrow/service/BorrowService.java
  server/src/main/java/com/book/village/server/domain/request/repository/RequestRepository.java
  server/src/test/java/com/book/village/server/domain/borrow/controller/BorrowControllerRestDocsTest.java
  server/src/test/java/com/book/village/server/statistics/borrowRank/BorrowRankRestDocsTest.java
Labels: [BE]김성수

#206 Fix/be/git
  server/src/main/java/com/book/village/server/domain/borrow/entity/Borrow.java
  server/src/main/java/com/book/village/server/domain/request/controller/RequestController.java
  server/src/main/java/com/book/village/server/domain/request/entity/RequestRank.java
  server/src/main/java/com/book/village/server/domain/request/mapper/RequestMapper.java
  server/src/main/java/com/book/village/server/domain/request/repository/RequestRepository.java
  server/src/main/java/com/book/village/server/domain/request/service/RequestService.java
  server/src/test/java/com/book/village/server/domain/borrow/controller/BorrowControllerRestDocsTest.java
  server/src/test/java/com/book/village/server/domain/request/RequestControllerRestDocsTest.java
Labels: [BE]박종혁

#248 feat/be/querydsl
  server/build.gradle
  server/src/main/java/com/book/village/server/config/QuerydslConfig.java
  server/src/main/java/com/book/village/server/domain/borrow/controller/BorrowController.java
  server/src/main/java/com/book/village/server/domain/borrow/entity/BorrowRank.java
  server/src/main/java/com/book/village/server/domain/borrow/mapper/BorrowMapper.java
  server/src/main/java/com/book/village/server/domain/borrow/repository/BorrowQuerydslRepository.java
  server/src/main/java/com/book/village/server/domain/borrow/repository/BorrowRepository.java
  server/src/main/java/com/book/village/server/domain/borrow/service/BorrowService.java
  server/src/main/java/com/book/village/server/domain/request/controller/RequestController.java
  server/src/main/java/com/book/village/server/domain/request/entity/RequestRank.java
  server/src/main/java/com/book/village/server/domain/request/mapper/RequestMapper.java
  server/src/main/java/com/book/village/server/domain/request/repository/RequestQuerydslRepository.java
  server/src/main/java/com/book/village/server/domain/request/repository/RequestRepository.java
  server/src/main/java/com/book/village/server/domain/request/service/RequestService.java
  server/src/test/java/com/book/village/server/statistics/RequestRank/requestRankRestDocsTest.java
  server/src/test/java/com/book/village/server/statistics/borrowRank/BorrowRankRestDocsTest.java
Labels: [BE]박종혁
